[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "saxsrs"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy>=1.20"]

[tool.maturin]
features = ["pyo3/extension-module"]